### PR TITLE
Create github action

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by Bisaloo** [comment]
I took a stab at this since @kathsherratt and I made some changes to this repo last week and there was no easy way to make sure our changes didn't break anything. Kath came up with the idea of a test PR (https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/536) but it still required some manual action.

Hopefully, this should be a start to allow automated testing of changes in the testing framework.

@sbfnk, @JADEUSC, I think I lost some of the context around https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/issues/8 and in particular this https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/issues/8#issuecomment-808553439. At the moment, the tests only run on a single PR but please let me know if it is necessary to run them on another one. It's something that we could control via an environment variable (and then run tests with 2 different values). Maybe running on a PR that adds metadata could be useful to make sure we don't break anything on this side either.

**Comment by JADEUSC** [comment]
You are right, changing things in the validation repo is always a little risky. The way I handled this in the DE/PL hub was to create a list of previous PRs that seem to be edge cases and make sure that the behavior on these PRs is as expected. I extended this list every time a new case popped up.
This is the main reason why I added the ability to check PRs by reference number back in with PR #11 (Currently this is only possible by changing the test-event.json file).  So whenever I made changes to the repository I checked the list of PRs locally and only merged if the result was as expected.  The problem I see with only one test file is that this file will simply not be enough to catch all possible combinations of weird behavior in pull requests :smile:

I think this process could also be automated, however, the problem would still be that the list will never be complete and there will always be a chance of a new edge case that will break some part. This was the case in the comment mentioned by @Bisaloo . In this case, I did not check PRs that do not contain any forecasts. 

My basic idea for automated tests would be to add in the ability to check forecasts by their reference number and automatically run the changes on a list of PRs where the expected result is known beforehand (eg old edge cases). If the results are as expected the check will succeed and the change can be merged to the main branch of the validation repo.

**Comment by Bisaloo** [comment]
Hmm, right. After reading your comment, I realize I've been thinking about this the wrong way by trying to test against an existing PR. In my opinion, what should be done is refactor the code to make it entirely self-contained and then have a collection of files to increase the [code coverage](https://en.wikipedia.org/wiki/Code_coverage) to 100%. I agree this does not guarantee we will catch *all* possible problems but it's already a very strong safeguard.

Unfortunately, we stumble again on the fact that I could easily do this in R but I'll struggle more in python (mostly because I don't know anything about packaging python code & testing frameworks for python).

**Comment by JADEUSC** [comment]
Right, unfortunately my experience with this is very limited as well.

**Pull request closed without merging**
